/**
 * server/layers.js
 * Static geo seed data – real named facilities, plants, projects
 * All coordinates are [lat, lon] following the app convention
 * toPointFeature converts to GeoJSON [lon, lat]
 */

export const layers = {
  plants: [
    // ── Wind ──────────────────────────────────────────────────────────────
    { id: 'plant-wind-uk-hornsea', name: 'Hornsea One', lat: 53.9, lon: 1.9, sector: 'Wind', subtype: 'Offshore WF', capacityMW: 1218, status: 'Operating', owner: 'Ørsted', updatedAt: '2026-03-01', regionTag: 'UK' },
    { id: 'plant-wind-uk-dogger', name: 'Dogger Bank A', lat: 54.7, lon: 2.3, sector: 'Wind', subtype: 'Offshore WF', capacityMW: 1200, status: 'Commissioning', owner: 'SSE/Equinor', updatedAt: '2026-03-01', regionTag: 'UK' },
    { id: 'plant-wind-texas-permian', name: 'Permian Basin Wind', lat: 31.5, lon: -102.5, sector: 'Wind', subtype: 'Onshore WF', capacityMW: 3000, status: 'Operating', owner: 'NextEra', updatedAt: '2026-02-28', regionTag: 'NAM' },
    { id: 'plant-wind-germany-north', name: 'NordSee Ost', lat: 54.4, lon: 7.7, sector: 'Wind', subtype: 'Offshore WF', capacityMW: 295, status: 'Operating', owner: 'RWE', updatedAt: '2026-02-20', regionTag: 'Germany' },
    { id: 'plant-wind-china-offshore', name: 'Rudong Offshore', lat: 32.6, lon: 121.3, sector: 'Wind', subtype: 'Offshore WF', capacityMW: 800, status: 'Operating', owner: 'CGNPC', updatedAt: '2026-02-15', regionTag: 'China' },
    { id: 'plant-wind-us-alta', name: 'Alta Wind Energy Center', lat: 35.1, lon: -118.3, sector: 'Wind', subtype: 'Onshore WF', capacityMW: 1548, status: 'Operating', owner: 'TerraGen', updatedAt: '2026-02-20', regionTag: 'NAM' },
    { id: 'plant-wind-iowa-mpo', name: 'MidAmerican Wind Portfolio', lat: 42.0, lon: -94.0, sector: 'Wind', subtype: 'Onshore WF', capacityMW: 5000, status: 'Operating', owner: 'MidAmerican Energy', updatedAt: '2026-02-18', regionTag: 'NAM' },
    { id: 'plant-wind-india-muppandal', name: 'Muppandal Wind Farm', lat: 8.2, lon: 77.6, sector: 'Wind', subtype: 'Onshore WF', capacityMW: 1500, status: 'Operating', owner: 'Various IPPs', updatedAt: '2026-01-20', regionTag: 'India' },
    { id: 'plant-wind-japan-noshiro', name: 'Noshiro Offshore Wind', lat: 39.9, lon: 140.0, sector: 'Wind', subtype: 'Offshore WF', capacityMW: 140, status: 'Operating', owner: 'Akita Offshore Wind', updatedAt: '2026-02-10', regionTag: 'APAC' },
    { id: 'plant-wind-aus-macarthur', name: 'Macarthur Wind Farm', lat: -38.0, lon: 142.1, sector: 'Wind', subtype: 'Onshore WF', capacityMW: 420, status: 'Operating', owner: 'Vestas/AGL', updatedAt: '2026-01-25', regionTag: 'APAC' },
    { id: 'plant-wind-sk-sinan', name: 'Sinan Offshore Wind', lat: 34.8, lon: 126.1, sector: 'Wind', subtype: 'Offshore WF', capacityMW: 400, status: 'Construction', owner: 'Korea Offshore Wind', updatedAt: '2026-02-22', regionTag: 'APAC' },
    // ── Solar ──────────────────────────────────────────────────────────────
    { id: 'plant-solar-india-bhadla', name: 'Bhadla Solar Park', lat: 27.5, lon: 71.9, sector: 'Solar', subtype: 'Utility PV', capacityMW: 2245, status: 'Operating', owner: 'NTPC/Adani', updatedAt: '2026-03-01', regionTag: 'India' },
    { id: 'plant-solar-xinjiang-hami', name: 'Hami Solar Base', lat: 42.8, lon: 93.5, sector: 'Solar', subtype: 'Utility PV', capacityMW: 5000, status: 'Operating', owner: 'CGN', updatedAt: '2026-02-28', regionTag: 'China' },
    { id: 'plant-solar-us-copper-mtn', name: 'Copper Mountain Solar', lat: 35.7, lon: -114.9, sector: 'Solar', subtype: 'Utility PV', capacityMW: 816, status: 'Operating', owner: 'Sempra', updatedAt: '2026-02-25', regionTag: 'NAM' },
    { id: 'plant-solar-es-nunez', name: 'Núñez de Balboa', lat: 38.4, lon: -6.5, sector: 'Solar', subtype: 'Utility PV', capacityMW: 500, status: 'Operating', owner: 'Iberdrola', updatedAt: '2026-02-20', regionTag: 'EMEA' },
    { id: 'plant-solar-us-ivanpah', name: 'Ivanpah CSP', lat: 35.6, lon: -115.5, sector: 'Solar', subtype: 'CSP', capacityMW: 392, status: 'Operating', owner: 'BrightSource', updatedAt: '2026-02-15', regionTag: 'NAM' },
    { id: 'plant-solar-us-topaz', name: 'Topaz Solar Farm', lat: 35.4, lon: -119.9, sector: 'Solar', subtype: 'Utility PV', capacityMW: 550, status: 'Operating', owner: 'BHE Renewables', updatedAt: '2026-02-12', regionTag: 'NAM' },
    { id: 'plant-solar-aus-limondale', name: 'Limondale Solar Farm', lat: -34.0, lon: 143.4, sector: 'Solar', subtype: 'Utility PV', capacityMW: 349, status: 'Operating', owner: 'Lightsource BP', updatedAt: '2026-02-10', regionTag: 'APAC' },
    { id: 'plant-solar-japan-setouchi', name: 'Setouchi Kirei Solar', lat: 34.5, lon: 134.2, sector: 'Solar', subtype: 'Utility PV', capacityMW: 235, status: 'Operating', owner: 'Toyo Engineering', updatedAt: '2026-02-08', regionTag: 'APAC' },
    { id: 'plant-solar-india-pavagada', name: 'Pavagada Solar Park', lat: 14.1, lon: 77.3, sector: 'Solar', subtype: 'Utility PV', capacityMW: 2050, status: 'Operating', owner: 'KPCL', updatedAt: '2026-02-05', regionTag: 'India' },
    // ── Hydro ──────────────────────────────────────────────────────────────
    { id: 'plant-hydro-three-gorges', name: 'Three Gorges Dam', lat: 30.8, lon: 111.0, sector: 'Hydro', subtype: 'Run-of-river', capacityMW: 22500, status: 'Operating', owner: 'CTGC', updatedAt: '2026-01-15', regionTag: 'China' },
    { id: 'plant-hydro-itaipu', name: 'Itaipu Binacional', lat: -25.4, lon: -54.6, sector: 'Hydro', subtype: 'Reservoir', capacityMW: 14000, status: 'Operating', owner: 'Brazil/Paraguay', updatedAt: '2026-01-10', regionTag: 'NAM' },
    { id: 'plant-hydro-bc', name: 'Peace River Hydro', lat: 56.0, lon: -122.7, sector: 'Hydro', subtype: 'Reservoir hydro', capacityMW: 2730, status: 'Operating', owner: 'BC Hydro', updatedAt: '2026-02-10', regionTag: 'NAM' },
    { id: 'plant-hydro-us-grandcoulee', name: 'Grand Coulee Dam', lat: 47.9, lon: -118.9, sector: 'Hydro', subtype: 'Reservoir', capacityMW: 6809, status: 'Operating', owner: 'USBR', updatedAt: '2026-01-10', regionTag: 'NAM' },
    { id: 'plant-hydro-us-hoover', name: 'Hoover Dam', lat: 36.0, lon: -114.7, sector: 'Hydro', subtype: 'Reservoir', capacityMW: 2080, status: 'Operating', owner: 'USBR', updatedAt: '2026-01-05', regionTag: 'NAM' },
    { id: 'plant-hydro-japan-kurobe', name: 'Kurobe Dam', lat: 36.6, lon: 137.7, sector: 'Hydro', subtype: 'Reservoir', capacityMW: 335, status: 'Operating', owner: 'Kansai Electric', updatedAt: '2026-01-15', regionTag: 'APAC' },
    { id: 'plant-hydro-india-tehri', name: 'Tehri Dam', lat: 30.4, lon: 78.5, sector: 'Hydro', subtype: 'Reservoir', capacityMW: 1000, status: 'Operating', owner: 'THDC', updatedAt: '2026-01-08', regionTag: 'India' },
    { id: 'plant-hydro-aus-snowy', name: 'Snowy Hydro 2.0', lat: -36.4, lon: 148.4, sector: 'Hydro', subtype: 'Pumped hydro', capacityMW: 2000, status: 'Under construction', owner: 'Snowy Hydro', updatedAt: '2026-02-20', regionTag: 'APAC' },
    // ── Geothermal ─────────────────────────────────────────────────────────
    { id: 'plant-geo-iceland-hs', name: 'Hellisheiði Power', lat: 64.0, lon: -21.4, sector: 'Geothermal', subtype: 'Flash steam', capacityMW: 303, status: 'Operating', owner: 'ON Power', updatedAt: '2026-01-20', regionTag: 'EMEA' },
    { id: 'plant-geo-us-geysers', name: 'The Geysers', lat: 38.8, lon: -122.8, sector: 'Geothermal', subtype: 'Dry steam', capacityMW: 725, status: 'Operating', owner: 'Calpine Corp', updatedAt: '2026-01-25', regionTag: 'NAM' },
    { id: 'plant-geo-nz-wairakei', name: 'Wairakei Power Station', lat: -38.6, lon: 176.1, sector: 'Geothermal', subtype: 'Flash steam', capacityMW: 116, status: 'Operating', owner: 'Contact Energy', updatedAt: '2026-01-18', regionTag: 'APAC' },
    { id: 'plant-geo-us-salton', name: 'Salton Sea Geothermal', lat: 33.2, lon: -115.6, sector: 'Geothermal', subtype: 'Flash steam', capacityMW: 340, status: 'Operating', owner: 'CalEnergy', updatedAt: '2026-01-20', regionTag: 'NAM' },
    { id: 'plant-geo-ph-makban', name: 'Makban Geothermal', lat: 14.1, lon: 121.5, sector: 'Geothermal', subtype: 'Flash steam', capacityMW: 458, status: 'Operating', owner: 'Aboitiz Power', updatedAt: '2026-01-15', regionTag: 'APAC' },
    { id: 'plant-geo-id-wayang', name: 'Wayang Windu', lat: -7.2, lon: 107.6, sector: 'Geothermal', subtype: 'Flash steam', capacityMW: 227, status: 'Operating', owner: 'Star Energy', updatedAt: '2026-01-12', regionTag: 'APAC' },
    { id: 'plant-geo-japan-hatchobaru', name: 'Hatchobaru Geothermal', lat: 33.1, lon: 131.2, sector: 'Geothermal', subtype: 'Double flash', capacityMW: 112, status: 'Operating', owner: 'Kyushu Electric', updatedAt: '2026-01-22', regionTag: 'APAC' },
    { id: 'plant-geo-us-fervo', name: 'Fervo Cape Station', lat: 38.5, lon: -118.2, sector: 'Geothermal', subtype: 'EGS', capacityMW: 400, status: 'Construction', owner: 'Fervo Energy', updatedAt: '2026-02-28', regionTag: 'NAM' },
    // ── Nuclear ────────────────────────────────────────────────────────────
    { id: 'plant-nuc-hinkley', name: 'Hinkley Point C', lat: 51.2, lon: -3.1, sector: 'Nuclear', subtype: 'EPR', capacityMW: 3200, status: 'Under construction', owner: 'EDF', updatedAt: '2026-03-02', regionTag: 'UK' },
    { id: 'plant-nuc-france-flamanville', name: 'Flamanville-3 EPR', lat: 49.5, lon: -1.9, sector: 'Nuclear', subtype: 'EPR', capacityMW: 1630, status: 'Commissioning', owner: 'EDF', updatedAt: '2026-02-28', regionTag: 'France' },
    { id: 'plant-nuc-us-vogtle', name: 'Vogtle Unit 4', lat: 33.1, lon: -81.8, sector: 'Nuclear', subtype: 'AP1000', capacityMW: 1117, status: 'Commissioning', owner: 'Georgia Power', updatedAt: '2026-03-01', regionTag: 'NAM' },
    { id: 'plant-nuc-china-haiyang', name: 'Haiyang AP1000', lat: 36.7, lon: 121.5, sector: 'Nuclear', subtype: 'AP1000', capacityMW: 2500, status: 'Operating', owner: 'SNPTC', updatedAt: '2026-02-20', regionTag: 'China' },
  ],

  storage: [
    { id: 'bess-aus-hornsdale', name: 'Hornsdale Power Reserve', lat: -33.1, lon: 138.0, sector: 'Storage', subtype: 'Li-ion BESS', capacityMW: 150, status: 'Operating', owner: 'Neoen/Tesla', updatedAt: '2026-02-28', regionTag: 'APAC' },
    { id: 'bess-uk-minety', name: 'Minety BESS', lat: 51.7, lon: -2.0, sector: 'Storage', subtype: 'Li-ion BESS', capacityMW: 350, status: 'Operating', owner: 'Harmony Energy', updatedAt: '2026-03-01', regionTag: 'UK' },
    { id: 'bess-ca-elkhorn', name: 'Elkhorn Battery', lat: 36.6, lon: -121.6, sector: 'Storage', subtype: 'Li-ion BESS', capacityMW: 182, status: 'Operating', owner: 'Vistra', updatedAt: '2026-02-27', regionTag: 'NAM' },
    { id: 'bess-texas-moss-landing', name: 'Moss Landing Phase 2', lat: 36.8, lon: -121.8, sector: 'Storage', subtype: 'Li-ion BESS', capacityMW: 300, status: 'Operating', owner: 'Monterey Bay', updatedAt: '2026-02-22', regionTag: 'NAM' },
    { id: 'bess-de-schwerin', name: 'Schwerin Flywheel', lat: 53.6, lon: 11.4, sector: 'Storage', subtype: 'Flywheel', capacityMW: 50, status: 'Operating', owner: 'Statkraft DE', updatedAt: '2026-02-15', regionTag: 'Germany' },
    { id: 'bess-cn-hubei-psps', name: 'Hubei Pumped Hydro', lat: 30.9, lon: 113.0, sector: 'Storage', subtype: 'Pumped hydro', capacityMW: 2400, status: 'Construction', owner: 'Three Gorges Corp', updatedAt: '2026-02-25', regionTag: 'China' },
    { id: 'bess-us-gateway', name: 'Gateway BESS', lat: 33.9, lon: -118.2, sector: 'Storage', subtype: 'Li-ion BESS', capacityMW: 250, status: 'Operating', owner: 'LS Power', updatedAt: '2026-02-20', regionTag: 'NAM' },
    { id: 'bess-aus-waratah', name: 'Waratah Super Battery', lat: -32.9, lon: 151.7, sector: 'Storage', subtype: 'Li-ion BESS', capacityMW: 850, status: 'Operating', owner: 'Akaysha Energy', updatedAt: '2026-02-22', regionTag: 'APAC' },
    { id: 'bess-japan-hokkaido', name: 'Hokkaido BESS', lat: 43.1, lon: 141.3, sector: 'Storage', subtype: 'Li-ion BESS', capacityMW: 100, status: 'Operating', owner: 'Hokkaido Electric', updatedAt: '2026-02-18', regionTag: 'APAC' },
    { id: 'bess-india-rajnandgaon', name: 'Rajnandgaon BESS', lat: 21.1, lon: 81.0, sector: 'Storage', subtype: 'Li-ion BESS', capacityMW: 500, status: 'Construction', owner: 'Greenko', updatedAt: '2026-02-15', regionTag: 'India' },
    { id: 'bess-uk-humber', name: 'Humber Flow Battery', lat: 53.7, lon: -0.4, sector: 'Storage', subtype: 'Flow battery', capacityMW: 100, status: 'Construction', owner: 'Humber Storage Co', updatedAt: '2026-02-27', regionTag: 'UK' },
  ],

  projects: [
    { id: 'proj-wind-us-vineyard', name: 'Vineyard Wind 1', lat: 41.4, lon: -70.8, sector: 'Wind', subtype: 'Offshore WF', capacityMW: 806, status: 'Under construction', owner: 'Avangrid/CIP', updatedAt: '2026-03-02', regionTag: 'NAM' },
    { id: 'proj-solar-india-gujarat', name: 'Khavda RE Park', lat: 23.8, lon: 68.5, sector: 'Solar', subtype: 'Utility PV', capacityMW: 30000, status: 'Under construction', owner: 'Adani Green', updatedAt: '2026-03-01', regionTag: 'India' },
    { id: 'proj-wind-de-he-dreieck', name: 'He Dreieck Wind', lat: 52.2, lon: 8.6, sector: 'Wind', subtype: 'Onshore WF', capacityMW: 120, status: 'Permitted', owner: 'EnBW', updatedAt: '2026-02-26', regionTag: 'Germany' },
    { id: 'proj-solar-es-helios-east', name: 'Helios East', lat: 39.3, lon: -1.9, sector: 'Solar', subtype: 'Utility PV', capacityMW: 500, status: 'Permitted', owner: 'Iberdrola', updatedAt: '2026-02-26', regionTag: 'EMEA' },
    { id: 'proj-wind-nz-clutha', name: 'Clutha Wind Farm', lat: -46.0, lon: 169.4, sector: 'Wind', subtype: 'Onshore WF', capacityMW: 240, status: 'Under construction', owner: 'Mercury NZ', updatedAt: '2026-02-20', regionTag: 'APAC' },
    { id: 'proj-nuc-us-smr-idaho', name: 'Nuscale CFPP', lat: 43.5, lon: -112.0, sector: 'Nuclear', subtype: 'SMR', capacityMW: 462, status: 'FEED', owner: 'NuScale/UAMPS', updatedAt: '2026-03-01', regionTag: 'NAM' },
    { id: 'proj-solar-sa-neom', name: 'NEOM Solar Array', lat: 28.0, lon: 35.2, sector: 'Solar', subtype: 'Utility PV', capacityMW: 4800, status: 'Development', owner: 'NEOM/ACWA', updatedAt: '2026-02-28', regionTag: 'EMEA' },
    { id: 'proj-solar-us-gemini', name: 'Gemini Solar + Storage', lat: 36.6, lon: -114.9, sector: 'Solar', subtype: 'Utility PV+BESS', capacityMW: 690, status: 'Under construction', owner: 'Quinbrook', updatedAt: '2026-02-26', regionTag: 'NAM' },
    { id: 'proj-solar-aus-suncat', name: 'Sun Cable Australia-Asia', lat: -19.5, lon: 134.5, sector: 'Solar', subtype: 'Utility PV+HVDC', capacityMW: 20000, status: 'Development', owner: 'Sun Cable', updatedAt: '2026-02-20', regionTag: 'APAC' },
    { id: 'proj-wind-us-revolution', name: 'Revolution Wind', lat: 41.1, lon: -71.4, sector: 'Wind', subtype: 'Offshore WF', capacityMW: 704, status: 'Under construction', owner: 'Ørsted/Eversource', updatedAt: '2026-02-28', regionTag: 'NAM' },
    { id: 'proj-wind-taiwan-changhua', name: 'Changhua Offshore Wind', lat: 24.1, lon: 120.3, sector: 'Wind', subtype: 'Offshore WF', capacityMW: 900, status: 'Under construction', owner: 'Ørsted/CIP', updatedAt: '2026-02-22', regionTag: 'APAC' },
    { id: 'proj-nuc-india-jaitapur', name: 'Jaitapur EPR', lat: 16.6, lon: 73.3, sector: 'Nuclear', subtype: 'EPR', capacityMW: 9900, status: 'Development', owner: 'NPCIL/EDF', updatedAt: '2026-02-25', regionTag: 'India' },
  ],

  hydrogen: [
    { id: 'h2-rotterdam-port', name: 'Rotterdam H2Hub', lat: 51.9, lon: 4.1, sector: 'Hydrogen', subtype: 'Green H2 hub', capacityMW: 1000, status: 'Development', owner: 'Shell/Port Rotterdam', updatedAt: '2026-03-01', regionTag: 'Netherlands' },
    { id: 'h2-germany-rhine', name: 'RhineGreen Hub', lat: 50.9, lon: 6.9, sector: 'Hydrogen', subtype: 'Green H2 hub', capacityMW: 200, status: 'Construction', owner: 'RhineGreen', updatedAt: '2026-02-29', regionTag: 'Germany' },
    { id: 'h2-chile-atacama', name: 'AustriaHydr Atacama', lat: -24.0, lon: -70.1, sector: 'Hydrogen', subtype: 'Green H2 export', capacityMW: 800, status: 'Development', owner: 'Enertrag/HIF', updatedAt: '2026-02-25', regionTag: 'NAM' },
    { id: 'h2-japan-jera', name: 'JERA Ammonia Co-firing', lat: 34.8, lon: 136.9, sector: 'Hydrogen', subtype: 'Ammonia terminal', capacityMW: 600, status: 'Approved', owner: 'JERA', updatedAt: '2026-02-22', regionTag: 'Japan' },
    { id: 'h2-us-gulf', name: 'Gulf Coast Electrolyzer', lat: 29.7, lon: -95.2, sector: 'Hydrogen', subtype: 'Electrolyzer', capacityMW: 120, status: 'Development', owner: 'GC Hydrogen LLC', updatedAt: '2026-02-25', regionTag: 'NAM' },
    { id: 'h2-india-green', name: 'NTPC Green H2 Pilot', lat: 23.0, lon: 72.5, sector: 'Hydrogen', subtype: 'Green H2 pilot', capacityMW: 50, status: 'Construction', owner: 'NTPC', updatedAt: '2026-02-20', regionTag: 'India' },
    { id: 'h2-aus-pilbara', name: 'Pilbara H2 Export', lat: -23.8, lon: 118.0, sector: 'Hydrogen', subtype: 'Green H2 export', capacityMW: 5000, status: 'Development', owner: 'ATCO/Woodside', updatedAt: '2026-02-18', regionTag: 'APAC' },
    { id: 'h2-us-appalachian', name: 'ARCH2 Appalachian Hub', lat: 38.3, lon: -81.6, sector: 'Hydrogen', subtype: 'H2 hub', capacityMW: 800, status: 'Development', owner: 'DOE/EQT', updatedAt: '2026-02-20', regionTag: 'NAM' },
    { id: 'h2-us-midwest', name: 'MachH2 Midwest Hub', lat: 41.9, lon: -87.6, sector: 'Hydrogen', subtype: 'H2 hub', capacityMW: 1000, status: 'Development', owner: 'DOE/BP', updatedAt: '2026-02-22', regionTag: 'NAM' },
    { id: 'h2-india-vizag', name: 'NTPC Vizag Green H2', lat: 17.7, lon: 83.3, sector: 'Hydrogen', subtype: 'Green H2 hub', capacityMW: 300, status: 'Construction', owner: 'NTPC', updatedAt: '2026-02-15', regionTag: 'India' },
    { id: 'h2-sk-incheon', name: 'SK E&S Incheon H2', lat: 37.5, lon: 126.7, sector: 'Hydrogen', subtype: 'Blue H2', capacityMW: 250, status: 'Construction', owner: 'SK E&S', updatedAt: '2026-02-12', regionTag: 'APAC' },
  ],

  ev: [
    { id: 'ev-tesla-gigafactory-nevada', name: 'Tesla Gigafactory Nevada', lat: 39.5, lon: -119.4, sector: 'EV', subtype: 'Gigafactory', capacityMW: 0, status: 'Operating', owner: 'Tesla', updatedAt: '2026-03-01', regionTag: 'NAM' },
    { id: 'ev-catl-thuringia', name: 'CATL Erfurt Gigafactory', lat: 50.9, lon: 11.0, sector: 'EV', subtype: 'Cell manufacturing', capacityMW: 0, status: 'Operating', owner: 'CATL', updatedAt: '2026-02-28', regionTag: 'Germany' },
    { id: 'ev-northvolt-skelleftea', name: 'Northvolt Ett', lat: 64.7, lon: 20.9, sector: 'EV', subtype: 'Cell manufacturing', capacityMW: 0, status: 'Operating', owner: 'Northvolt', updatedAt: '2026-02-25', regionTag: 'EMEA' },
    { id: 'ev-v2g-uk', name: 'Northern Buses V2G', lat: 53.5, lon: -1.5, sector: 'EV', subtype: 'Depot V2G pilot', capacityMW: 12, status: 'Pilot', owner: 'Northern Buses', updatedAt: '2026-03-03', regionTag: 'UK' },
    { id: 'ev-byd-shenzhen', name: 'BYD Shenzhen Factory', lat: 22.6, lon: 114.1, sector: 'EV', subtype: 'Gigafactory', capacityMW: 0, status: 'Operating', owner: 'BYD', updatedAt: '2026-02-20', regionTag: 'China' },
    { id: 'ev-tesla-texas', name: 'Tesla Giga Texas', lat: 30.2, lon: -97.6, sector: 'EV', subtype: 'Gigafactory', capacityMW: 0, status: 'Operating', owner: 'Tesla', updatedAt: '2026-02-28', regionTag: 'NAM' },
    { id: 'ev-rivian-normal', name: 'Rivian Normal Factory', lat: 40.5, lon: -89.0, sector: 'EV', subtype: 'EV assembly', capacityMW: 0, status: 'Operating', owner: 'Rivian', updatedAt: '2026-02-22', regionTag: 'NAM' },
    { id: 'ev-hyundai-ulsan', name: 'Hyundai Ulsan EV Plant', lat: 35.5, lon: 129.3, sector: 'EV', subtype: 'EV assembly', capacityMW: 0, status: 'Operating', owner: 'Hyundai', updatedAt: '2026-02-18', regionTag: 'APAC' },
    { id: 'ev-toyota-japan', name: 'Toyota Motomachi EV Line', lat: 35.1, lon: 137.0, sector: 'EV', subtype: 'EV assembly', capacityMW: 0, status: 'Operating', owner: 'Toyota', updatedAt: '2026-02-15', regionTag: 'APAC' },
    { id: 'ev-tata-pune', name: 'Tata Motors Pune EV', lat: 18.5, lon: 73.9, sector: 'EV', subtype: 'EV assembly', capacityMW: 0, status: 'Operating', owner: 'Tata Motors', updatedAt: '2026-02-10', regionTag: 'India' },
    { id: 'ev-lg-michigan', name: 'LG Energy Michigan', lat: 42.3, lon: -83.0, sector: 'EV', subtype: 'Cell manufacturing', capacityMW: 0, status: 'Construction', owner: 'LG Energy Solution', updatedAt: '2026-02-25', regionTag: 'NAM' },
    { id: 'ev-sg-comfortdelgro', name: 'ComfortDelGro Fleet Depot', lat: 1.33, lon: 103.85, sector: 'EV', subtype: 'Fleet depot V2G', capacityMW: 8, status: 'Pilot', owner: 'ComfortDelGro', updatedAt: '2026-02-22', regionTag: 'Singapore' },
  ],

  nuclear: [
    { id: 'nuc-smr-us-idaho-demo', name: 'Idaho SMR Demo', lat: 43.6, lon: -112.0, sector: 'Nuclear', subtype: 'SMR demo', capacityMW: 300, status: 'FEED', owner: 'Idaho SMR', updatedAt: '2026-03-03', regionTag: 'NAM' },
    { id: 'nuc-gen4-france', name: 'HexaNuke Gen IV', lat: 46.5, lon: 2.6, sector: 'Nuclear', subtype: 'Gen IV pilot', capacityMW: 150, status: 'Concept', owner: 'HexaNuke', updatedAt: '2026-02-20', regionTag: 'France' },
    { id: 'nuc-china-sanmen', name: 'Sanmen Nuclear AP1000', lat: 29.1, lon: 121.7, sector: 'Nuclear', subtype: 'AP1000', capacityMW: 2500, status: 'Operating', owner: 'SNPTC', updatedAt: '2026-02-12', regionTag: 'China' },
    { id: 'nuc-canada-ontario-refurb', name: 'Darlington Refurbishment', lat: 43.9, lon: -78.7, sector: 'Nuclear', subtype: 'CANDU refurb', capacityMW: 3512, status: 'Under construction', owner: 'OPG', updatedAt: '2026-02-28', regionTag: 'NAM' },
    { id: 'nuc-us-palo-verde', name: 'Palo Verde Nuclear', lat: 33.4, lon: -112.9, sector: 'Nuclear', subtype: 'PWR', capacityMW: 3937, status: 'Operating', owner: 'APS', updatedAt: '2026-02-15', regionTag: 'NAM' },
    { id: 'nuc-japan-takahama', name: 'Takahama Nuclear', lat: 35.5, lon: 135.5, sector: 'Nuclear', subtype: 'PWR', capacityMW: 3392, status: 'Operating', owner: 'Kansai Electric', updatedAt: '2026-02-10', regionTag: 'APAC' },
    { id: 'nuc-sk-shin-hanul', name: 'Shin Hanul Units 3-4', lat: 37.1, lon: 129.4, sector: 'Nuclear', subtype: 'APR1400', capacityMW: 2800, status: 'Under construction', owner: 'KHNP', updatedAt: '2026-02-20', regionTag: 'APAC' },
    { id: 'nuc-india-kudankulam', name: 'Kudankulam Units 3-4', lat: 8.2, lon: 77.7, sector: 'Nuclear', subtype: 'VVER-1000', capacityMW: 2000, status: 'Under construction', owner: 'NPCIL', updatedAt: '2026-02-18', regionTag: 'India' },
    { id: 'nuc-uk-sizewell-c', name: 'Sizewell C EPR', lat: 52.2, lon: 1.6, sector: 'Nuclear', subtype: 'EPR', capacityMW: 3200, status: 'Approved', owner: 'EDF/HMG', updatedAt: '2026-03-01', regionTag: 'UK' },
  ],

  policy: [
    { id: 'policy-eu-flex', name: 'EU Flexibility Act', lat: 50.8, lon: 4.4, sector: 'Policy', subtype: 'Grid flexibility', status: 'Effective', owner: 'EU Commission', updatedAt: '2026-03-02', regionTag: 'EMEA' },
    { id: 'policy-us-ancillary', name: 'FERC Ancillary Reform', lat: 38.9, lon: -77.0, sector: 'Policy', subtype: 'Grid policy', status: 'Filed', owner: 'FERC', updatedAt: '2026-02-28', regionTag: 'NAM' },
    { id: 'policy-india-solar-pli', name: 'India Solar PLI Round 2', lat: 28.6, lon: 77.2, sector: 'Policy', subtype: 'Manufacturing subsidy', status: 'Active', owner: 'MNRE', updatedAt: '2026-03-01', regionTag: 'India' },
    { id: 'policy-uk-cfd-ar6', name: 'UK CfD Allocation Round 6', lat: 51.5, lon: -0.12, sector: 'Policy', subtype: 'Auction', status: 'Active', owner: 'DESNZ', updatedAt: '2026-03-03', regionTag: 'UK' },
    { id: 'policy-cn-ets', name: 'China ETS Phase 3', lat: 39.9, lon: 116.4, sector: 'Policy', subtype: 'Carbon market', status: 'Effective', owner: 'MEE', updatedAt: '2026-02-25', regionTag: 'China' },
    { id: 'policy-us-ira-storage', name: 'IRA Storage ITC Rules', lat: 37.0, lon: -95.0, sector: 'Policy', subtype: 'Tax credit', status: 'Active', owner: 'IRS/DOE', updatedAt: '2026-02-20', regionTag: 'NAM' },
    { id: 'policy-us-epa-emissions', name: 'EPA Power Plant Rule', lat: 38.9, lon: -77.0, sector: 'Policy', subtype: 'Emissions standard', status: 'Active', owner: 'EPA', updatedAt: '2026-02-28', regionTag: 'NAM' },
    { id: 'policy-japan-gx', name: 'Japan GX Transition Bonds', lat: 35.7, lon: 139.7, sector: 'Policy', subtype: 'Green finance', status: 'Active', owner: 'METI', updatedAt: '2026-02-25', regionTag: 'APAC' },
    { id: 'policy-aus-cap', name: 'Australia Capacity Investment Scheme', lat: -35.3, lon: 149.1, sector: 'Policy', subtype: 'Capacity auction', status: 'Active', owner: 'DCCEEW', updatedAt: '2026-02-22', regionTag: 'APAC' },
    { id: 'policy-sk-re100', name: 'South Korea RE100 Target', lat: 37.6, lon: 127.0, sector: 'Policy', subtype: 'RE mandate', status: 'Active', owner: 'MOTIE', updatedAt: '2026-02-18', regionTag: 'APAC' },
  ],

  transmission: [
    { id: 'tx-nsea-grid', name: 'North Sea Grid Link', path: [[55, 5], [56, 3], [57, 0], [56, -2], [55, -3]], capacityMW: 2000, status: 'Approved', updatedAt: '2026-03-01', regionTag: 'EMEA' },
    { id: 'tx-us-east-hvdc', name: 'US East Coast HVDC', path: [[40, -74], [39, -77], [38, -80], [36, -82]], capacityMW: 3000, status: 'Development', updatedAt: '2026-02-28', regionTag: 'NAM' },
    { id: 'tx-uk-nl-intertie', name: 'BritNed Interconnector', path: [[51.9, 1.3], [52.1, 2.5], [52.4, 3.5], [51.9, 4.2]], capacityMW: 1800, status: 'Operational', updatedAt: '2026-02-21', regionTag: 'EMEA' },
    { id: 'tx-hu-balkan', name: 'Balkans HVDC', path: [[47.5, 19.0], [46.1, 17.3], [45.2, 15.9], [43.8, 20.4]], capacityMW: 1000, status: 'Approved', updatedAt: '2026-02-18', regionTag: 'EMEA' },
    { id: 'tx-us-grain-belt', name: 'Grain Belt Express HVDC', path: [[37.0, -100.0], [38.5, -95.0], [39.5, -91.0], [39.8, -89.5]], capacityMW: 5000, status: 'Approved', updatedAt: '2026-02-25', regionTag: 'NAM' },
    { id: 'tx-us-soo-green', name: 'SOO Green HVDC Link', path: [[43.1, -89.4], [42.5, -90.0], [41.9, -89.5], [41.7, -87.7]], capacityMW: 2100, status: 'Development', updatedAt: '2026-02-20', regionTag: 'NAM' },
    { id: 'tx-aus-energy-connect', name: 'EnergyConnect SA-NSW', path: [[-34.8, 138.6], [-33.5, 142.0], [-32.5, 144.0], [-31.9, 146.0]], capacityMW: 800, status: 'Under construction', updatedAt: '2026-02-22', regionTag: 'APAC' },
    { id: 'tx-india-green-corridor', name: 'India Green Corridor', path: [[27.0, 71.5], [26.0, 74.0], [24.0, 77.0], [21.0, 79.0]], capacityMW: 4000, status: 'Under construction', updatedAt: '2026-02-15', regionTag: 'APAC' },
  ],

  resource: [
    { id: 'res-sahara-solar', ring: [[30, -5], [30, 30], [15, 30], [15, -5], [30, -5]], metric: 'Solar DNI', value: '>6 kWh/m²/d', updatedAt: '2026-03-01', regionTag: 'MEA' },
    { id: 'res-north-sea-wind', ring: [[51, -4], [51, 8], [57, 8], [57, -4], [51, -4]], metric: 'Wind Speed', value: '>9 m/s mean', updatedAt: '2026-03-01', regionTag: 'EMEA' },
    { id: 'res-patagonia-wind', ring: [[-40, -70], [-40, -60], [-55, -60], [-55, -70], [-40, -70]], metric: 'Wind Speed', value: '>10 m/s mean', updatedAt: '2026-02-28', regionTag: 'LATAM' },
    { id: 'res-us-southwest-solar', ring: [[30, -115], [30, -105], [37, -105], [37, -115], [30, -115]], metric: 'Solar DNI', value: '>6.5 kWh/m²/d', updatedAt: '2026-02-25', regionTag: 'NAM' },
    { id: 'res-us-great-plains-wind', ring: [[35, -103], [35, -95], [48, -95], [48, -103], [35, -103]], metric: 'Wind Speed', value: '>8 m/s mean', updatedAt: '2026-02-25', regionTag: 'NAM' },
    { id: 'res-aus-solar-belt', ring: [[-20, 120], [-20, 145], [-30, 145], [-30, 120], [-20, 120]], metric: 'Solar DNI', value: '>6 kWh/m²/d', updatedAt: '2026-02-20', regionTag: 'APAC' },
    { id: 'res-india-solar-corridor', ring: [[22, 68], [22, 78], [30, 78], [30, 68], [22, 68]], metric: 'Solar DNI', value: '>5.5 kWh/m²/d', updatedAt: '2026-02-18', regionTag: 'APAC' },
  ],
}

export const events = [
  { id: 'evt-1', layer: 'plants', sector: 'Solar', title: 'Khavda RE Park milestone: first 5 GW energised', updatedAt: '2026-03-01T08:00:00Z', lat: 23.8, lon: 68.5 },
  { id: 'evt-2', layer: 'storage', sector: 'Storage', title: 'Minety BESS completes primary frequency response contract', updatedAt: '2026-03-01T06:30:00Z', lat: 51.7, lon: -2.0 },
  { id: 'evt-3', layer: 'hydrogen', sector: 'Hydrogen', title: 'Rotterdam H2Hub announces €2 bn Phase 1 FID', updatedAt: '2026-03-02T18:15:00Z', lat: 51.9, lon: 4.1 },
  { id: 'evt-4', layer: 'ev', sector: 'EV', title: 'Northern Buses V2G fleet expands to 200 vehicles', updatedAt: '2026-03-03T09:10:00Z', lat: 53.5, lon: -1.5 },
  { id: 'evt-5', layer: 'nuclear', sector: 'Nuclear', title: 'Vogtle Unit 4 reaches commercial operation', updatedAt: '2026-03-02T14:30:00Z', lat: 33.1, lon: -81.8 },
  { id: 'evt-6', layer: 'projects', sector: 'Wind', title: 'Vineyard Wind 1 installs first monopile foundation', updatedAt: '2026-03-03T11:00:00Z', lat: 41.4, lon: -70.8 },
  { id: 'evt-7', layer: 'policy', sector: 'Policy', title: 'UK CfD AR6 results: 6.7 GW solar/wind cleared', updatedAt: '2026-03-03T14:00:00Z', lat: 51.5, lon: -0.12 },
  { id: 'evt-8', layer: 'plants', sector: 'Solar', title: 'Gemini Solar Farm reaches 50% completion in Nevada', updatedAt: '2026-03-02T10:00:00Z', lat: 36.6, lon: -114.9 },
  { id: 'evt-9', layer: 'storage', sector: 'Storage', title: 'Waratah Super Battery begins commercial operation in NSW', updatedAt: '2026-03-03T07:00:00Z', lat: -32.9, lon: 151.7 },
  { id: 'evt-10', layer: 'projects', sector: 'Wind', title: 'Revolution Wind installs first turbine off Rhode Island', updatedAt: '2026-03-02T12:00:00Z', lat: 41.1, lon: -71.4 },
  { id: 'evt-11', layer: 'nuclear', sector: 'Nuclear', title: 'Shin Hanul Unit 3 achieves first concrete in South Korea', updatedAt: '2026-03-01T16:00:00Z', lat: 37.1, lon: 129.4 },
  { id: 'evt-12', layer: 'hydrogen', sector: 'Hydrogen', title: 'MachH2 Midwest Hub receives $1.2B DOE funding', updatedAt: '2026-03-02T09:30:00Z', lat: 41.9, lon: -87.6 },
  { id: 'evt-13', layer: 'ev', sector: 'EV', title: 'Hyundai Ulsan begins mass production of IONIQ 9', updatedAt: '2026-03-03T04:00:00Z', lat: 35.5, lon: 129.3 },
]
