export const layers = {
  plants: [
    {
      id: 'plant-wind-uk',
      name: 'NorthSea Wind JV',
      lat: 54.4,
      lon: 1.2,
      sector: 'Wind',
      subtype: 'Offshore wind',
      capacityMW: 1200,
      status: 'Operational',
      owner: 'NorthSea Wind JV',
      updatedAt: '2026-03-01',
      regionTag: 'UK',
    },
    {
      id: 'plant-solar-india',
      name: 'Surya Power Phase 3',
      lat: 24.5,
      lon: 72.6,
      sector: 'Solar',
      subtype: 'Utility PV',
      capacityMW: 800,
      status: 'Commissioning',
      owner: 'Surya Power',
      updatedAt: '2026-03-02',
      regionTag: 'India',
    },
    {
      id: 'plant-hydro-ca',
      name: 'Peace River Hydro',
      lat: 52.8,
      lon: -122.4,
      sector: 'Hydro',
      subtype: 'Reservoir hydro',
      capacityMW: 1500,
      status: 'Operational',
      owner: 'BC Hydro',
      updatedAt: '2026-02-22',
      regionTag: 'NAM',
    },
    {
      id: 'plant-geo-iceland',
      name: 'Iceland Geo Complex',
      lat: 64.7,
      lon: -19.5,
      sector: 'Geothermal',
      subtype: 'Flash steam',
      capacityMW: 300,
      status: 'Operational',
      owner: 'Iceland Geo',
      updatedAt: '2026-02-19',
      regionTag: 'EMEA',
    },
  ],
  storage: [
    {
      id: 'storage-ca',
      name: 'BayGrid BESS',
      lat: 37.3,
      lon: -121.9,
      sector: 'Storage',
      subtype: 'Li-ion BESS',
      capacityMW: 350,
      status: 'Operational',
      owner: 'Silicon Valley ISO',
      updatedAt: '2026-03-02',
      regionTag: 'NAM',
    },
    {
      id: 'storage-uk',
      name: 'Humber Flow Battery',
      lat: 53.7,
      lon: -0.4,
      sector: 'Storage',
      subtype: 'Flow battery',
      capacityMW: 100,
      status: 'Construction',
      owner: 'Humber Storage Co.',
      updatedAt: '2026-02-27',
      regionTag: 'UK',
    },
  ],
  projects: [
    {
      id: 'project-wind-us',
      name: 'Prairie Wind West',
      lat: 42.1,
      lon: -100.2,
      sector: 'Wind',
      subtype: 'Onshore wind',
      capacityMW: 600,
      status: 'Under construction',
      owner: 'Frontier Renewables',
      updatedAt: '2026-03-01',
      regionTag: 'NAM',
    },
    {
      id: 'project-solar-es',
      name: 'Helios East',
      lat: 39.3,
      lon: -1.9,
      sector: 'Solar',
      subtype: 'Utility PV',
      capacityMW: 500,
      status: 'Permitted',
      owner: 'Iberia Solar',
      updatedAt: '2026-02-26',
      regionTag: 'EMEA',
    },
  ],
  hydrogen: [
    {
      id: 'h2-ger',
      name: 'RhineGreen Hub',
      lat: 50.9,
      lon: 6.9,
      sector: 'Hydrogen',
      subtype: 'Green H2 hub',
      capacityMW: 200,
      status: 'Construction',
      owner: 'RhineGreen',
      updatedAt: '2026-02-29',
      regionTag: 'Germany',
    },
    {
      id: 'h2-us',
      name: 'Gulf Coast Electrolyzer',
      lat: 29.7,
      lon: -95.2,
      sector: 'Hydrogen',
      subtype: 'Electrolyzer',
      capacityMW: 120,
      status: 'Development',
      owner: 'GC Hydrogen LLC',
      updatedAt: '2026-02-25',
      regionTag: 'NAM',
    },
  ],
  ev: [
    {
      id: 'ev-v2g-uk',
      name: 'Northern Buses V2G',
      lat: 53.5,
      lon: -1.5,
      sector: 'EV',
      subtype: 'Depot V2G pilot',
      capacityMW: 12,
      status: 'Pilot',
      owner: 'Northern Buses',
      updatedAt: '2026-03-03',
      regionTag: 'UK',
    },
    {
      id: 'ev-hpc-us',
      name: 'BayCharge HPC Hub',
      lat: 37.8,
      lon: -122.2,
      sector: 'EV',
      subtype: '350kW charging',
      capacityMW: 8,
      status: 'Operational',
      owner: 'BayCharge',
      updatedAt: '2026-02-26',
      regionTag: 'NAM',
    },
  ],
  nuclear: [
    {
      id: 'nuclear-smr-us',
      name: 'Idaho SMR Demo',
      lat: 43.6,
      lon: -112.0,
      sector: 'Nuclear',
      subtype: 'SMR demo',
      capacityMW: 300,
      status: 'FEED',
      owner: 'Idaho SMR',
      updatedAt: '2026-03-03',
      regionTag: 'NAM',
    },
    {
      id: 'nuclear-gen4-fr',
      name: 'HexaNuke Gen IV',
      lat: 46.5,
      lon: 2.6,
      sector: 'Nuclear',
      subtype: 'Gen IV pilot',
      capacityMW: 150,
      status: 'Concept',
      owner: 'HexaNuke',
      updatedAt: '2026-02-20',
      regionTag: 'France',
    },
  ],
  policy: [
    {
      id: 'policy-eu-flex',
      name: 'EU Flexibility Act dispatch phase',
      lat: 50.1,
      lon: 8.7,
      sector: 'Policy',
      subtype: 'Policy',
      status: 'Effective',
      owner: 'EU',
      updatedAt: '2026-03-02',
      regionTag: 'EMEA',
    },
    {
      id: 'policy-us-ancillary',
      name: 'US ancillary reform for storage',
      lat: 38.9,
      lon: -77.0,
      sector: 'Policy',
      subtype: 'Policy',
      status: 'Filed',
      owner: 'FERC',
      updatedAt: '2026-02-28',
      regionTag: 'NAM',
    },
  ],
  transmission: [
    {
      id: 'tx-uk-intertie',
      name: 'UK-NL Intertie',
      path: [
        [52.0, 1.4],
        [53.0, 2.0],
        [53.5, 3.0],
        [53.6, 4.5],
      ],
      capacityMW: 1800,
      status: 'Operational',
      updatedAt: '2026-02-21',
    },
    {
      id: 'tx-us-solar',
      name: 'Southwest HVDC',
      path: [
        [34.1, -118.2],
        [35.0, -110.0],
        [36.2, -104.8],
      ],
      capacityMW: 2000,
      status: 'Construction',
      updatedAt: '2026-02-27',
    },
  ],
  resource: [
    {
      id: 'resource-solar-na',
      ring: [
        [36.0, -115.0],
        [38.0, -105.0],
        [33.0, -102.0],
        [31.0, -110.0],
      ],
      metric: 'Solar irradiance',
      value: 2100,
      updatedAt: '2026-02-18',
    },
    {
      id: 'resource-wind-nsea',
      ring: [
        [55.0, 0.0],
        [58.0, 2.0],
        [56.0, 6.0],
        [54.0, 3.0],
      ],
      metric: 'Wind speed',
      value: 9.4,
      updatedAt: '2026-02-12',
    },
  ],
}

export const events = [
  {
    id: 'evt-1',
    layer: 'plants',
    sector: 'Solar',
    title: 'Surya Power Phase 3 advanced to commissioning',
    updatedAt: '2026-03-02T08:00:00Z',
    lat: 24.5,
    lon: 72.6,
  },
  {
    id: 'evt-2',
    layer: 'storage',
    sector: 'Storage',
    title: 'BayGrid BESS firmware updated for grid services',
    updatedAt: '2026-03-02T06:30:00Z',
    lat: 37.3,
    lon: -121.9,
  },
  {
    id: 'evt-3',
    layer: 'hydrogen',
    sector: 'Hydrogen',
    title: 'RhineGreen Hub awarded offtake contract',
    updatedAt: '2026-03-01T18:15:00Z',
    lat: 50.9,
    lon: 6.9,
  },
  {
    id: 'evt-4',
    layer: 'ev',
    sector: 'EV',
    title: 'Depot V2G pilot expands to 200 buses',
    updatedAt: '2026-03-03T09:10:00Z',
    lat: 53.5,
    lon: -1.5,
  },
  {
    id: 'evt-5',
    layer: 'nuclear',
    sector: 'Nuclear',
    title: 'SMR demo clears grid interconnection study',
    updatedAt: '2026-03-02T14:30:00Z',
    lat: 43.6,
    lon: -112.0,
  },
]
